CREATE TABLE QMS_QUALITY_PROGRAM
(
  QUALITY_PROGRAM_ID NUMBER NOT NULL
, PROGRAM_ID NUMBER NOT NULL
, PROGRAM_NAME VARCHAR2(20)
, START_DATE DATE
, END_DATE DATE
, CATEGORY_NAME VARCHAR2(20)
, MAX_POINTS NUMBER
, MAX_SCORE NUMBER
, REC_UPDATE_DATE DATE
, CURRENT_FLAG NUMBER
, MODIFIED_BY VARCHAR2(20)
, CONSTRAINT QMS_QUALITY_PROGRAM_PK PRIMARY KEY
  (
    QUALITY_PROGRAM_ID
  )
  ENABLE
);
