CREATE OR REPLACE FORCE VIEW "ADMIN"."FINAL_DIRTY_VIEW" ("QUALITY_MEASURE_SK", "SCORE", "DATE_SK", "OU_SK") AS 
(SELECT T1.QUALITY_MEASURE_SK, T1.SCORE, T1.DATE_SK, T1.OU_SK FROM 
( 
SELECT A.QUALITY_MEASURE_SK, ROUND(TO_NUMBER(10)-TO_NUMBER(AVG(A.SCORE))) AS SCORE, A.DATE_SK, DO.OU_SK
FROM FACT_MIPS_QMS A 
INNER JOIN DIM_DATE DD ON A.DATE_SK = DD.DATE_SK 
INNER JOIN DIM_LOCATION DL ON A.LOCATION_SK = DL.LOCATION_SK
INNER JOIN DIM_FACILITY DF ON DF.FACILITY_SK = DL.FACILITY_SK
INNER JOIN DIM_OU DO ON DO.OU_SK = DF.OU_SK
INNER JOIN DIM_QUALITY_MEASURE DQM ON A.QUALITY_MEASURE_SK = DQM.QUALITY_MEASURE_SK
INNER JOIN DIM_QUALITY_PROGRAM DQP ON DQP.QUALITY_PROGRAM_SK = DQM.QUALITY_PROGRAM_SK AND LOWER(DQP.CATEGORY_NAME) = LOWER('QUALITY')
GROUP BY A.QUALITY_MEASURE_SK, A.DATE_SK, DO.OU_SK
) T1
UNION ALL
SELECT CATEGORY AS QUALITY_MEASURE_SK, -TO_NUMBER(SUM_SCORE) AS SCORE, DD.DATE_SK, DO.OU_SK
FROM 
(
SELECT '1000' AS CATEGORY, AVG(TO_NUMBER(T1.SCORE)) AS SUM_SCORE, T1.CALENDAR_DATE, T1.OU_ID
FROM 
( 
SELECT TO_NUMBER(DQP.MAX_POINTS) AS SCORE, DD.CALENDAR_DATE AS CALENDAR_DATE, DO.OU_ID
FROM FACT_MIPS_QMS A 
INNER JOIN DIM_DATE DD ON A.DATE_SK = DD.DATE_SK
INNER JOIN DIM_LOCATION DL ON A.LOCATION_SK = DL.LOCATION_SK
INNER JOIN DIM_FACILITY DF ON DL.FACILITY_SK = DF.FACILITY_SK
INNER JOIN DIM_OU DO ON DO.OU_SK = DF.OU_SK
INNER JOIN DIM_QUALITY_MEASURE DQM ON A.QUALITY_MEASURE_SK = DQM.QUALITY_MEASURE_SK
INNER JOIN DIM_QUALITY_PROGRAM DQP ON DQP.QUALITY_PROGRAM_SK = DQM.QUALITY_PROGRAM_SK
) T1
GROUP BY T1.CALENDAR_DATE, T1.OU_ID
) A
INNER JOIN DIM_DATE DD ON A.CALENDAR_DATE = DD.CALENDAR_DATE 
INNER JOIN (SELECT T1.* FROM DIM_OU T1, (SELECT OU_ID, MAX(INGESTION_DATE) AS MAXDATETIME FROM DIM_OU GROUP BY OU_ID) T2 
WHERE T1.OU_ID = T2.OU_ID and T1.INGESTION_DATE = T2.MAXDATETIME) DO ON A.OU_ID = DO.OU_ID);