CREATE OR REPLACE FORCE VIEW "ADMIN"."HEDIS_SUMMARY_VIEW" ("QUALITY_MEASURE_SK", "NUMERATOR", "DENOMINATOR", "RATIO", "PERIOD", "FACILITY_NAME", "OU_NAME", "CATEGORY_NAME", "PROGRAM_NAME", "MAX_POINTS", "MAX_SCORE", "MEASURE_TITLE", "PRODUCT_NAME", "PLAN_NAME", "P50", "P90") AS 
(SELECT DISTINCT FHQ.QUALITY_MEASURE_SK, FHQ.NUMERATOR, FHQ.DENOMINATOR, FHQ.RATIO, DD.PERIOD, DF.FACILITY_NAME, DO.OU_NAME, DQP.CATEGORY_NAME, DQP.PROGRAM_NAME, DQP.MAX_POINTS, DQP.MAX_SCORE, DQM.MEASURE_TITLE, DPP.PRODUCT_NAME, DPP.PLAN_NAME, DQPE.P50, DQPE.P90
FROM FACT_HEDIS_QMS FHQ
INNER JOIN DIM_DATE DD ON DD.DATE_SK = FHQ.DATE_SK
INNER JOIN DIM_FACILITY DF ON DF.FACILITY_SK = FHQ.FACILITY_SK
INNER JOIN DIM_OU DO ON DO.OU_SK = DF.OU_SK
INNER JOIN DIM_LOCATION DL ON DL.FACILITY_SK = FHQ.FACILITY_SK
INNER JOIN DIM_QUALITY_MEASURE DQM ON DQM.QUALITY_MEASURE_SK = FHQ.QUALITY_MEASURE_SK
INNER JOIN DIM_QUALITY_PROGRAM DQP ON DQP.QUALITY_PROGRAM_SK = DQM.QUALITY_PROGRAM_SK
INNER JOIN DIM_QUALITY_PERCENTILE DQPE ON DQPE.QUALITY_MEASURE_SK = DQM.QUALITY_MEASURE_SK
INNER JOIN DIM_PRODUCT_PLAN DPP ON DPP.PRODUCT_PLAN_SK = FHQ.PRODUCT_PLAN_SK);