CREATE OR REPLACE FORCE VIEW "ADMIN"."HEDIS_MEMBER_VIEW" ("MEMBER_SK", "MEMBER_ID", "NAME", "GENDER", "CITY", "DOB", "YEAR", "AGE", "AGE_GROUP", "QUALITY_MEASURE_SK", "AMOUNT_PAID", "HCC_SCORE", "COMPLIANT", "REASON") AS 
(SELECT DISTINCT ENC.MEMBER_SK, ENC.MEMBER_ID, (ENC.FIRST_NAME||' '||ENC.MIDDLE_NAME||' '||ENC.LAST_NAME) AS NAME, ENC.GENDER, ENC.CITY, TO_CHAR(TO_DATE(SUBSTR(ENC.DATE_OF_BIRTH_SK, 1, 4) || '-' || SUBSTR(ENC.DATE_OF_BIRTH_SK, 5,2) || '-' || SUBSTR(ENC.DATE_OF_BIRTH_SK, 7,2),'YYYY-MM-DD'),'YYYY-MM-DD') AS DOB, TO_CHAR(TO_DATE(SUBSTR(ENC.DATE_OF_BIRTH_SK, 1, 4) || '-' || SUBSTR(ENC.DATE_OF_BIRTH_SK, 5,2) || '-' || SUBSTR(ENC.DATE_OF_BIRTH_SK, 7,2),'YYYY-MM-DD'),'YYYY') AS YEAR, ((TO_DATE('2018-12-31','YYYY-MM-DD') - TO_DATE(SUBSTR(ENC.DATE_OF_BIRTH_SK, 1, 4) || '-' || SUBSTR(ENC.DATE_OF_BIRTH_SK, 5,2) || '-' || SUBSTR(ENC.DATE_OF_BIRTH_SK, 7,2),'YYYY-MM-DD')))/365.25 AS AGE, DA.AGE_GROUP, FH.QUALITY_MEASURE_SK, FC.AMOUNT_PAID, FHRS.HCC_SCORE, FH.IN_NUMERATOR AS COMPLIANT, FH.REASON AS REASON
FROM DIM_MEMBER ENC
LEFT OUTER JOIN FACT_CLAIMS FC ON FC.MEMBER_SK = ENC.MEMBER_SK
LEFT OUTER JOIN FACT_HEDIS_GAPS_IN_CARE FH ON FH.MEMBER_SK = ENC.MEMBER_SK
LEFT OUTER JOIN FACT_HCC_RISK_SCORE FHRS ON FHRS.MEMBER_SK = ENC.MEMBER_SK
LEFT OUTER JOIN DIM_MEASURE_AGE_GROUP DA ON DA.QUALITY_MEASURE_SK = FH.QUALITY_MEASURE_SK 
WHERE ((TO_DATE('2018-12-31','YYYY-MM-DD') - TO_DATE(SUBSTR(ENC.DATE_OF_BIRTH_SK, 1, 4) || '-' || SUBSTR(ENC.DATE_OF_BIRTH_SK, 5,2) || '-' || SUBSTR(ENC.DATE_OF_BIRTH_SK, 7,2),'YYYY-MM-DD')))/365.25 BETWEEN DA.START_AGE AND DA.END_AGE
AND FH.DATE_SK = (SELECT MAX(FHG.DATE_SK) FROM FACT_HEDIS_GAPS_IN_CARE FHG WHERE FH.MEMBER_SK = FHG.MEMBER_SK));
