CREATE OR REPLACE FORCE VIEW "ADMIN"."MIPS_SUMMARY_VIEW" ("QUALITY_MEASURE_SK", "NUMERATOR", "DENOMINATOR", "RATIO", "PERIOD", "FACILITY_NAME", "OU_NAME", "CATEGORY_NAME", "PROGRAM_NAME", "MAX_POINTS", "MAX_SCORE", "MEASURE_TITLE", "P50", "P90", "LOCATION_SK", "LOCATION_NAME") AS 
(SELECT DISTINCT FMQ.QUALITY_MEASURE_SK, FMQ.NUMERATOR, FMQ.DENOMINATOR, FMQ.RATIO, DD.PERIOD, DF.FACILITY_NAME, DO.OU_NAME, DQP.CATEGORY_NAME, DQP.PROGRAM_NAME, DQP.MAX_POINTS, DQP.MAX_SCORE, DQM.MEASURE_TITLE, DQPE.P50, DQPE.P90, DL.location_sk, dl.location_name
FROM FACT_MIPS_QMS FMQ
INNER JOIN DIM_DATE DD ON DD.DATE_SK = FMQ.DATE_SK
INNER JOIN DIM_LOCATION DL ON DL.LOCATION_SK = FMQ.LOCATION_SK
INNER JOIN DIM_FACILITY DF ON DF.FACILITY_SK = DL.FACILITY_SK
INNER JOIN DIM_OU DO ON DO.OU_SK = DF.OU_SK
INNER JOIN DIM_QUALITY_MEASURE DQM ON DQM.QUALITY_MEASURE_SK = FMQ.QUALITY_MEASURE_SK
INNER JOIN DIM_QUALITY_PROGRAM DQP ON DQP.QUALITY_PROGRAM_SK = DQM.QUALITY_PROGRAM_SK
INNER JOIN DIM_QUALITY_PERCENTILE DQPE ON DQPE.QUALITY_MEASURE_SK = DQM.QUALITY_MEASURE_SK);