CREATE OR REPLACE FORCE VIEW "ADMIN"."SHALINI_VIEW" ("Claims", "Achievement %", "Measure Cat", "Score", "Period", "Numerator", "Facility ID", "Facility Name", "Measure Name", "Measure Code", "Plan Code", "Plan Name", "Start", "End", "Product Name") AS 
  (SELECT DISTINCT
  FCM.CLAIMS_ID AS "Claims",
  FHQ.RATIO AS "Achievement %", 
  QQP.CATEGORY_NAME AS "Measure Cat",
  CASE 
    WHEN (FHQ.RATIO*100) > 90 THEN 3 
    WHEN (FHQ.RATIO*100) BETWEEN 50 AND 90 THEN 2
    ELSE 1
  END AS "Score",
  FHQ.DATE_SK AS "Period",
  FHQ.NUMERATOR AS "Numerator",
  DF.FACILITY_SK AS "Facility ID", 
  DF.FACILITY_NAME AS "Facility Name",
  DQM.MEASURE_TITLE AS "Measure Name", 
  DQM.QUALITY_MEASURE_SK AS "Measure Code",
  DP.PRODUCT_PLAN_ID AS "Plan Code", 
  DP.PLAN_NAME AS "Plan Name",
  FMM.MEMBER_PLAN_START_DATE_SK AS "Start", 
  FMM.MEMBER_PLAN_END_DATE_SK as "End",
  DP.PRODUCT_NAME AS "Product Name"
FROM FACT_HEDIS_QMS FHQ
INNER JOIN DIM_QUALITY_MEASURE DQM ON DQM.QUALITY_MEASURE_SK = FHQ.QUALITY_MEASURE_SK
INNER JOIN DIM_QUALITY_PROGRAM QQP ON QQP.QUALITY_PROGRAM_SK = DQM.QUALITY_PROGRAM_SK
INNER JOIN DIM_PRODUCT_PLAN DP ON DP.PRODUCT_PLAN_SK = FHQ.PRODUCT_PLAN_SK
INNER JOIN DIM_FACILITY DF ON DF.FACILITY_SK = FHQ.FACILITY_SK
INNER JOIN FACT_MEMBERSHIP FMM ON FMM.PRODUCT_PLAN_SK = DP.PRODUCT_PLAN_SK
INNER JOIN FACT_CLAIMS FCM ON FCM.MEMBER_SK = FMM.MEMBER_SK);