CREATE OR REPLACE FORCE VIEW "ADMIN"."SUBSCRIPTION_VIEW" AS
SELECT COUNT(FMM.MEMBER_SK) AS `SUBSCRIPTION`, DPM.PRODUCT_PLAN_ID
FROM FACT_MEMBERSHIP FMM
INNER JOIN DIM_PRODUCT_PLAN DPM ON DPM.PRODUCT_PLAN_SK = FMM.PRODUCT_PLAN_SK
GROUP BY DPM.PRODUCT_PLAN_ID;