CREATE OR REPLACE FORCE VIEW "ADMIN"."WATERFALL_VIEW" ("QUALITY_MEASURE_SK", "SCORE", "DATE_SK", "OU_SK") AS 
(SELECT "QUALITY_MEASURE_SK","SCORE","DATE_SK","OU_SK" FROM FINAL_DIRTY_VIEW WHERE QUALITY_MEASURE_SK = '1000'
UNION ALL
SELECT "QUALITY_MEASURE_SK","SCORE","DATE_SK","OU_SK" FROM FINAL_DIRTY_VIEW WHERE QUALITY_MEASURE_SK <> '1000'
UNION ALL
SELECT '1002' AS QUALITY_MEASURE_SK, SCORE, DATE_SK, OU_SK FROM
(
SELECT -(AVG(A.SCORE) + SUM(B.SCORE)) AS SCORE, A.DATE_SK, A.OU_SK FROM FINAL_DIRTY_VIEW A 
INNER JOIN FINAL_DIRTY_VIEW B ON A.DATE_SK = B.DATE_SK AND A.OU_SK = B.OU_SK
WHERE B.QUALITY_MEASURE_SK <> '1000' AND a.QUALITY_MEASURE_SK = '1000' 
GROUP BY A.DATE_SK, A.OU_SK
)
UNION ALL
SELECT '1003' AS QUALITY_MEASURE_SK, -SUM (SCORE), DATE_SK, OU_SK FROM
(
SELECT -(AVG(A.SCORE) + SUM(B.SCORE)) AS SCORE, A.DATE_SK, A.OU_SK FROM FINAL_DIRTY_VIEW A 
INNER JOIN FINAL_DIRTY_VIEW B ON A.DATE_SK = B.DATE_SK AND A.OU_SK = B.OU_SK
WHERE B.QUALITY_MEASURE_SK <> '1000' AND a.QUALITY_MEASURE_SK = '1000' 
GROUP BY A.DATE_SK, A.OU_SK
)
GROUP BY DATE_SK, OU_SK
UNION ALL
(
SELECT '1004' AS QUALITY_MEASURE_SK, 0-AVG (A.BONUS) AS SCORE, A.DATE_SK, DO.OU_SK
FROM FACT_MIPS_QMS A 
INNER JOIN DIM_DATE DD ON A.DATE_SK = DD.DATE_SK 
INNER JOIN DIM_LOCATION DL ON A.LOCATION_SK = DL.LOCATION_SK
INNER JOIN DIM_FACILITY DF ON DF.FACILITY_SK = DL.FACILITY_SK
INNER JOIN DIM_OU DO ON DO.OU_SK = DF.OU_SK
INNER JOIN DIM_QUALITY_MEASURE DQM ON A.QUALITY_MEASURE_SK = DQM.QUALITY_MEASURE_SK
INNER JOIN DIM_QUALITY_PROGRAM DQP ON DQP.QUALITY_PROGRAM_SK = DQM.QUALITY_PROGRAM_SK AND LOWER(DQP.CATEGORY_NAME) = LOWER('QUALITY')
GROUP BY A.DATE_SK, DO.OU_SK
)
UNION ALL
SELECT '1005' AS QUALITY_MEASURE_SK, 0-SUM (SCORE), DATE_SK, OU_SK FROM
(
SELECT '1003' AS QUALITY_MEASURE_SK, 0-SUM (SCORE) AS SCORE, DATE_SK, OU_SK FROM
(
SELECT -(AVG(A.SCORE) + SUM(B.SCORE)) AS SCORE, A.DATE_SK, A.OU_SK FROM FINAL_DIRTY_VIEW A 
INNER JOIN FINAL_DIRTY_VIEW B ON A.DATE_SK = B.DATE_SK AND A.OU_SK = B.OU_SK
WHERE B.QUALITY_MEASURE_SK <> '1000' AND a.QUALITY_MEASURE_SK = '1000' 
GROUP BY A.DATE_SK, A.OU_SK
)
GROUP BY DATE_SK, OU_SK
UNION ALL
(
SELECT '1004' AS QUALITY_MEASURE_SK, 0-AVG (A.BONUS) AS SCORE, A.DATE_SK, DO.OU_SK
FROM FACT_MIPS_QMS A 
INNER JOIN DIM_DATE DD ON A.DATE_SK = DD.DATE_SK 
INNER JOIN DIM_LOCATION DL ON A.LOCATION_SK = DL.LOCATION_SK
INNER JOIN DIM_FACILITY DF ON DF.FACILITY_SK = DL.FACILITY_SK
INNER JOIN DIM_OU DO ON DO.OU_SK = DF.OU_SK
INNER JOIN DIM_QUALITY_MEASURE DQM ON A.QUALITY_MEASURE_SK = DQM.QUALITY_MEASURE_SK
INNER JOIN DIM_QUALITY_PROGRAM DQP ON DQP.QUALITY_PROGRAM_SK = DQM.QUALITY_PROGRAM_SK AND LOWER(DQP.CATEGORY_NAME) = LOWER('QUALITY')
GROUP BY A.DATE_SK, DO.OU_SK)
)
GROUP BY DATE_SK, OU_SK);