--------------------------------------------------------
--  File created - Monday-May-28-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QMS_MEASURE_TYPE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."QMS_MEASURE_TYPE" 
   (	"MEASURE_TYPE_ID" VARCHAR2(100 BYTE), 
	"MEASURE_TYPE_NAME" VARCHAR2(100 BYTE), 
	"MEASURE_TYPE_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"REC_UPDATE_DATE" TIMESTAMP (6), 
	"CURRENT_FLAG" VARCHAR2(1 BYTE), 
	"MODIFIED_BY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.QMS_MEASURE_TYPE
SET DEFINE OFF;
Insert into ADMIN.QMS_MEASURE_TYPE (MEASURE_TYPE_ID,MEASURE_TYPE_NAME,MEASURE_TYPE_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1','Composite','Composite',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_TYPE (MEASURE_TYPE_ID,MEASURE_TYPE_NAME,MEASURE_TYPE_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('2','Cost/Resource Use','Cost/Resource Use',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_TYPE (MEASURE_TYPE_ID,MEASURE_TYPE_NAME,MEASURE_TYPE_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('3','Efficiency','Efficiency',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_TYPE (MEASURE_TYPE_ID,MEASURE_TYPE_NAME,MEASURE_TYPE_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('4','Intermediate Outcome','Intermediate Outcome',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_TYPE (MEASURE_TYPE_ID,MEASURE_TYPE_NAME,MEASURE_TYPE_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('5','Outcome','Outcome',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_TYPE (MEASURE_TYPE_ID,MEASURE_TYPE_NAME,MEASURE_TYPE_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('6','Patient Engagement/Experience','Patient Engagement/Experience',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_TYPE (MEASURE_TYPE_ID,MEASURE_TYPE_NAME,MEASURE_TYPE_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('7','Patient Perspective','Patient Perspective',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_TYPE (MEASURE_TYPE_ID,MEASURE_TYPE_NAME,MEASURE_TYPE_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('8','Patient Reported Outcome','Patient Reported Outcome',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_TYPE (MEASURE_TYPE_ID,MEASURE_TYPE_NAME,MEASURE_TYPE_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('9','Process','Process',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_TYPE (MEASURE_TYPE_ID,MEASURE_TYPE_NAME,MEASURE_TYPE_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('10','Structure','Structure',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
--------------------------------------------------------
--  DDL for Index SYS_C0011502
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0011502" ON "ADMIN"."QMS_MEASURE_TYPE" ("MEASURE_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table QMS_MEASURE_TYPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."QMS_MEASURE_TYPE" MODIFY ("MEASURE_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_TYPE" MODIFY ("MEASURE_TYPE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_TYPE" MODIFY ("REC_UPDATE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_TYPE" MODIFY ("CURRENT_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_TYPE" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_TYPE" ADD PRIMARY KEY ("MEASURE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
