--------------------------------------------------------
--  File created - Monday-May-28-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QMS_MEASURE_STATUS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."QMS_MEASURE_STATUS" 
   (	"MEASURE_STATUS_ID" VARCHAR2(100 BYTE), 
	"MEASURE_STATUS_NAME" VARCHAR2(100 BYTE), 
	"MEASURE_STATUS_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"REC_UPDATE_DATE" TIMESTAMP (6), 
	"CURRENT_FLAG" VARCHAR2(1 BYTE), 
	"MODIFIED_BY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.QMS_MEASURE_STATUS
SET DEFINE OFF;
Insert into ADMIN.QMS_MEASURE_STATUS (MEASURE_STATUS_ID,MEASURE_STATUS_NAME,MEASURE_STATUS_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1','New','New',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STATUS (MEASURE_STATUS_ID,MEASURE_STATUS_NAME,MEASURE_STATUS_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('2','In-Progress','In-Progress',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STATUS (MEASURE_STATUS_ID,MEASURE_STATUS_NAME,MEASURE_STATUS_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('3','Review','Review',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STATUS (MEASURE_STATUS_ID,MEASURE_STATUS_NAME,MEASURE_STATUS_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('4','Re-work','Re-work',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STATUS (MEASURE_STATUS_ID,MEASURE_STATUS_NAME,MEASURE_STATUS_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('5','Approved','Approved',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STATUS (MEASURE_STATUS_ID,MEASURE_STATUS_NAME,MEASURE_STATUS_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('6','Completed','Completed',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
--------------------------------------------------------
--  DDL for Index SYS_C0011496
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0011496" ON "ADMIN"."QMS_MEASURE_STATUS" ("MEASURE_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table QMS_MEASURE_STATUS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."QMS_MEASURE_STATUS" MODIFY ("MEASURE_STATUS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_STATUS" MODIFY ("MEASURE_STATUS_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_STATUS" MODIFY ("REC_UPDATE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_STATUS" MODIFY ("CURRENT_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_STATUS" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_STATUS" ADD PRIMARY KEY ("MEASURE_STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
