--------------------------------------------------------
--  File created - Monday-May-28-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QMS_USER_MASTER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."QMS_USER_MASTER" 
   (	"USER_ID" VARCHAR2(100 BYTE), 
	"USER_NAME" VARCHAR2(1000 BYTE), 
	"USER_LOGINID" VARCHAR2(1000 BYTE), 
	"PASSWORD" VARCHAR2(1000 BYTE), 
	"USER_EMAIL" VARCHAR2(1000 BYTE), 
	"LAST_LOGIN" TIMESTAMP (6), 
	"USER_ROLE_ID" VARCHAR2(1000 BYTE), 
	"REC_UPDATE_DATE" TIMESTAMP (6), 
	"CURRENT_FLAG" VARCHAR2(1 BYTE), 
	"MODIFIED_BY" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.QMS_USER_MASTER
SET DEFINE OFF;
Insert into ADMIN.QMS_USER_MASTER (USER_ID,USER_NAME,USER_LOGINID,PASSWORD,USER_EMAIL,LAST_LOGIN,USER_ROLE_ID,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1','Raghu','raghu','Password123','raghu@itcinfotech.com',to_timestamp('06-DEC-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Role Id',to_timestamp('06-DEC-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_USER_MASTER (USER_ID,USER_NAME,USER_LOGINID,PASSWORD,USER_EMAIL,LAST_LOGIN,USER_ROLE_ID,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('2','Jeewan','jeewan','Password123','jeewan@itcinfotech.com',to_timestamp('06-DEC-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Role Id',to_timestamp('06-DEC-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','jeewan');
--------------------------------------------------------
--  DDL for Index SYS_C0011484
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0011484" ON "ADMIN"."QMS_USER_MASTER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table QMS_USER_MASTER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."QMS_USER_MASTER" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_USER_MASTER" MODIFY ("USER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_USER_MASTER" MODIFY ("USER_LOGINID" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_USER_MASTER" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_USER_MASTER" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_USER_MASTER" MODIFY ("USER_ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_USER_MASTER" MODIFY ("REC_UPDATE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_USER_MASTER" MODIFY ("CURRENT_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_USER_MASTER" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_USER_MASTER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
