--------------------------------------------------------
--  File created - Monday-May-28-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QMS_QUALITY_PROGRAM
--------------------------------------------------------

  CREATE TABLE "ADMIN"."QMS_QUALITY_PROGRAM" 
   (	"QUALITY_PROGRAM_ID" VARCHAR2(100 BYTE), 
	"PROGRAM_ID" VARCHAR2(100 BYTE), 
	"PROGRAM_NAME" VARCHAR2(100 BYTE), 
	"CATEGORY_NAME" VARCHAR2(100 BYTE), 
	"MAX_POINTS" NUMBER(*,0), 
	"MAX_SCORE" NUMBER(*,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"REC_CREATE_DATE" TIMESTAMP (6), 
	"REC_UPDATE_DATE" TIMESTAMP (6), 
	"CURRENT_FLAG" VARCHAR2(1 BYTE), 
	"MODIFIED_BY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.QMS_QUALITY_PROGRAM
SET DEFINE OFF;
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1001','10001','Merit-Based Incentive Payment System (MIPS) Program','Quality',60,50,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1002','10001','Merit-Based Incentive Payment System (MIPS) Program','Cost',10,10,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1003','10001','Merit-Based Incentive Payment System (MIPS) Program','ACI',155,25,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1004','10001','Merit-Based Incentive Payment System (MIPS) Program','IA',40,15,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1005','10002','Accountable Care Organization (ACO)',null,null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1006','10003','Medicare Shared Savings Program','Quality',null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1007','10003','Medicare Shared Savings Program',null,null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1008','10004','The Healthcare Effectiveness Data and Information Set (HEDIS)',null,null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1009','10004','The Healthcare Effectiveness Data and Information Set (HEDIS)','Effectiveness of Care',null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1010','10004','The Healthcare Effectiveness Data and Information Set (HEDIS)','Access/Availability of Care',null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1011','10004','The Healthcare Effectiveness Data and Information Set (HEDIS)','Utilization',null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1012','10004','The Healthcare Effectiveness Data and Information Set (HEDIS)','Relative Resouirce Use',null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1013','10004','The Healthcare Effectiveness Data and Information Set (HEDIS)','Health Plan Descriptive Information',null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1014','10002','Accountable Care Organization (ACO)','Care Coordination/Patient Safety',null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1015','10002','Accountable Care Organization (ACO)','Preventive Health',null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1016','10002','Accountable Care Organization (ACO)','At-Risk Population CAD',null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1017','10002','Accountable Care Organization (ACO)','At-Risk Population IVD',null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1018','10002','Accountable Care Organization (ACO)','At-Risk Population Hypertension',null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1019','10002','Accountable Care Organization (ACO)','At-Risk Population Diabetes',null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_QUALITY_PROGRAM (QUALITY_PROGRAM_ID,PROGRAM_ID,PROGRAM_NAME,CATEGORY_NAME,MAX_POINTS,MAX_SCORE,START_DATE,END_DATE,REC_CREATE_DATE,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1020','10005','CMS Star',null,null,null,to_date('01-JAN-17','DD-MON-RR'),null,to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
--------------------------------------------------------
--  DDL for Index SYS_C0011521
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0011521" ON "ADMIN"."QMS_QUALITY_PROGRAM" ("QUALITY_PROGRAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table QMS_QUALITY_PROGRAM
--------------------------------------------------------

  ALTER TABLE "ADMIN"."QMS_QUALITY_PROGRAM" MODIFY ("QUALITY_PROGRAM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_QUALITY_PROGRAM" MODIFY ("PROGRAM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_QUALITY_PROGRAM" MODIFY ("PROGRAM_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_QUALITY_PROGRAM" MODIFY ("START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_QUALITY_PROGRAM" MODIFY ("REC_CREATE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_QUALITY_PROGRAM" MODIFY ("REC_UPDATE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_QUALITY_PROGRAM" MODIFY ("CURRENT_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_QUALITY_PROGRAM" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_QUALITY_PROGRAM" ADD PRIMARY KEY ("QUALITY_PROGRAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
