--------------------------------------------------------
--  File created - Monday-May-28-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QMS_MEASURE_STEWARD
--------------------------------------------------------

  CREATE TABLE "ADMIN"."QMS_MEASURE_STEWARD" 
   (	"STEWARD_TYPE_ID" VARCHAR2(100 BYTE), 
	"STEWARD_NAME" VARCHAR2(1500 BYTE), 
	"STEWARD_DESCRIPTION" VARCHAR2(1500 BYTE), 
	"REC_UPDATE_DATE" TIMESTAMP (6), 
	"CURRENT_FLAG" VARCHAR2(1 BYTE), 
	"MODIFIED_BY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.QMS_MEASURE_STEWARD
SET DEFINE OFF;
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('1','Academy of Nutrition and Dietetics','Academy of Nutrition and Dietetics',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('2','Agency for Healthcare Research & Quality (AHRQ)','Agency for Healthcare Research & Quality (AHRQ)',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('3','American Academy of Dermatology','American Academy of Dermatology',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('4','American Academy of Neurology','American Academy of Neurology',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('5','American Academy of Neurology, American Psychological Association','American Academy of Neurology, American Psychological Association',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('6','American Academy of Ophthalmology','American Academy of Ophthalmology',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('7','American Academy of Otolaryngology-Head and Neck Surgery','American Academy of Otolaryngology-Head and Neck Surgery',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('8','American Association of Eye and Ear Centers of Excellence and The Australian Council on Healthcare Standards','American Association of Eye and Ear Centers of Excellence and The Australian Council on Healthcare Standards',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('9','American College of Cardiology','American College of Cardiology',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('10','American College of Cardiology/American Heart Association','American College of Cardiology/American Heart Association',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('11','American College of Emergency Physicians','American College of Emergency Physicians',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('12','American College of Emergency Physicians (ACEP)','American College of Emergency Physicians (ACEP)',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('13','American College of Emergency Physicians (previous steward Partners-Brigham & Women)','American College of Emergency Physicians (previous steward Partners-Brigham & Women)',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('14','American College of Gastroenterology/ American Gastroenterological Association/AGA/American Society for Gastrointestinal Endoscopy','American College of Gastroenterology/ American Gastroenterological Association/AGA/American Society for Gastrointestinal Endoscopy',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('15','American College of Radiology','American College of Radiology',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('16','American College of Radiology/American Medical Association-Physician Consortium for Performance Improvement/National Committee for Quality Assurance','American College of Radiology/American Medical Association-Physician Consortium for Performance Improvement/National Committee for Quality Assurance',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('17','American College of Rheumatology','American College of Rheumatology',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('18','American College of Surgeons','American College of Surgeons',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('19','American Gastroenterological Association','American Gastroenterological Association',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('20','American Gastroenterological Association/American Association for the Study of Liver Disease/Physician Consortium for Performance Improvement','American Gastroenterological Association/American Association for the Study of Liver Disease/Physician Consortium for Performance Improvement',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('21','American Heart Association','American Heart Association',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('22','American Heart Association/American Society of Anesthesiologists/CDC Paul Coverdale National Acute Stroke Registry (PCNASR)','American Heart Association/American Society of Anesthesiologists/CDC Paul Coverdale National Acute Stroke Registry (PCNASR)',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('23','American Medical Association','American Medical Association',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('24','American Medical Association - Physician Consortium for Performance Improvement (AMA-PCPI)','American Medical Association - Physician Consortium for Performance Improvement (AMA-PCPI)',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('25','American Medical Association-ÉPhysician Consortium for Performance Improvement/American College of Cardiology/American Heart Association','American Medical Association-ÉPhysician Consortium for Performance Improvement/American College of Cardiology/American Heart Association',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('26','American Podiatric Medical Association','American Podiatric Medical Association',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('27','American Society for Gastrointestinal Endoscopy','American Society for Gastrointestinal Endoscopy',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('28','American Society for Radiation Oncology (ASTRO)','American Society for Radiation Oncology (ASTRO)',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('29','American Society of Addiction Medicine','American Society of Addiction Medicine',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('30','American Society of Anesthesiologists','American Society of Anesthesiologists',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('31','American Society of Clinical Oncology','American Society of Clinical Oncology',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('32','American Society of Hematology','American Society of Hematology',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('33','American Society of Plastic Surgeons','American Society of Plastic Surgeons',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('34','American Thoracic Society','American Thoracic Society',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('35','American Urogynecologic Society','American Urogynecologic Society',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('36','American Urological Association','American Urological Association',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('37','American Urological Association Education and Research','American Urological Association Education and Research',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('38','AQC/ASHA','AQC/ASHA',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('39','Audiology Quality Consortium/American Speech Language Hearing Association','Audiology Quality Consortium/American Speech Language Hearing Association',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('40','Being developed by CMS','Being developed by CMS',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('41','Center for Clinical Informatics','Center for Clinical Informatics',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('42','Center for Quality Assessment and Improvement in Mental Health','Center for Quality Assessment and Improvement in Mental Health',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('43','Centers for Disease Control and Prevention (CDC)','Centers for Disease Control and Prevention (CDC)',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('44','Centers for Disease Control and Prevention, Centers for Medicare & Medicaid Services','Centers for Disease Control and Prevention, Centers for Medicare & Medicaid Services',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('45','Centers for Medicare & Medicaid Services (CMS)','Centers for Medicare & Medicaid Services (CMS)',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('46','Centers for Medicare and Medicaid Services/Florida Medical Quality Assurance Incorporated','Centers for Medicare and Medicaid Services/Florida Medical Quality Assurance Incorporated',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('47','CMS','CMS',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('48','College of American Pathologists','College of American Pathologists',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('49','Eugene Gastroenterology Consultants, PC Oregon Endoscopy Center, LLC','Eugene Gastroenterology Consultants, PC Oregon Endoscopy Center, LLC',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('50','Focus on Therapeutic Outcomes, Inc.','Focus on Therapeutic Outcomes, Inc.',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('51','Health Resources and Services Administration (HRSA)','Health Resources and Services Administration (HRSA)',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('52','Health Resources and Services Administration (HRSA) - HIV/AIDS Bureau','Health Resources and Services Administration (HRSA) - HIV/AIDS Bureau',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('53','Heart Rhythm Society','Heart Rhythm Society',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('54','IAC','IAC',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('55','Indian Health Service','Indian Health Service',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('56','Infectious Diseases Society of America','Infectious Diseases Society of America',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('57','Minnesota Community Measurement','Minnesota Community Measurement',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('58','National Committee for Quality Assurance (NCQA)','National Committee for Quality Assurance (NCQA)',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('59','National Minority Quality Forum','National Minority Quality Forum',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('60','Not Specified','Not Specified',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('61','Office of the National Coordinator for Health Information Technology','Office of the National Coordinator for Health Information Technology',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('62','OptumInsight','OptumInsight',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('63','Oregon Health and Sciences University','Oregon Health and Sciences University',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('64','Oregon Urology Institute','Oregon Urology Institute',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('65','PCPI(R) Foundation (PCPI[R])','PCPI(R) Foundation (PCPI[R])',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('66','Pharmacy Quality Alliance (PQA, Inc.)','Pharmacy Quality Alliance (PQA, Inc.)',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('67','Physician Consortium for Performance Improvement (PCPI)','Physician Consortium for Performance Improvement (PCPI)',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('68','RAND Corporation','RAND Corporation',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('69','Renal Physicians Association','Renal Physicians Association',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('70','Renal Physicians Association; joint copyright with American Medical Association é¼Physician Consortium for Performance Improvement','Renal Physicians Association; joint copyright with American Medical Association é¼Physician Consortium for Performance Improvement',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('71','Society for Vascular Surgeons','Society for Vascular Surgeons',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('72','Society for Vascular Surgery','Society for Vascular Surgery',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('73','Society of Gynecologic Oncology','Society of Gynecologic Oncology',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('74','Society of Interventional Radiology','Society of Interventional Radiology',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('75','Society of Thoracic Surgeons','Society of Thoracic Surgeons',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('76','The Heart Rhythm Society','The Heart Rhythm Society',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('77','The Society for Vascular Surgery','The Society for Vascular Surgery',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('78','Wisconsin Collaborative for Healthcare Quality','Wisconsin Collaborative for Healthcare Quality',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
Insert into ADMIN.QMS_MEASURE_STEWARD (STEWARD_TYPE_ID,STEWARD_NAME,STEWARD_DESCRIPTION,REC_UPDATE_DATE,CURRENT_FLAG,MODIFIED_BY) values ('79','Yale University','Yale University',to_timestamp('01-AUG-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Y','raghu');
--------------------------------------------------------
--  DDL for Index SYS_C0011551
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0011551" ON "ADMIN"."QMS_MEASURE_STEWARD" ("STEWARD_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table QMS_MEASURE_STEWARD
--------------------------------------------------------

  ALTER TABLE "ADMIN"."QMS_MEASURE_STEWARD" MODIFY ("STEWARD_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_STEWARD" MODIFY ("STEWARD_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_STEWARD" MODIFY ("REC_UPDATE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_STEWARD" MODIFY ("CURRENT_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_STEWARD" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."QMS_MEASURE_STEWARD" ADD PRIMARY KEY ("STEWARD_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
