/*===============================================================================================================================================
 DDL for DIM_TABLES 
=================================================================================================================================================*/
CREATE TABLE "DIM_DATE" 
   ("DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CALENDAR_DATE" DATE,
	"DAY_NUMBER_IN_MONTH" NUMBER(38,0),
	"DAY_OF_WEEK_NAME" VARCHAR2(100 BYTE),
	"DAY_OF_WEEK_NUMBER" NUMBER(38,0),
	"DAY_WEEK_ABBRV" VARCHAR2(100 BYTE),
	"DAY_NUMBER_IN_YEAR" NUMBER(38,0),
	"WEEK_NUMBER_IN_YEAR" NUMBER(38,0),
	"MONTH_ABBRV" VARCHAR2(100 BYTE),
	"MONTH_NUMBER" NUMBER(38,0),
	"MONTH_CODE" VARCHAR2(100 BYTE),
	"MONTH_END_DATE" VARCHAR2(100 BYTE),
	"QUARTER_NAME" VARCHAR2(100 BYTE),
	"YEAR" NUMBER(38,0),
	"PERIOD" DATE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("DATE_SK")
  );

CREATE TABLE "DIM_DEPARTMENT" 
   ("DEPARTMENT_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DEPARTMENT_ID" NUMBER(38,0) NOT NULL ENABLE,
	"DEPARTMENT_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOCATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("DEPARTMENT_SK")
  );

CREATE TABLE "DIM_FACILITY" 
   ("FACILITY_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"FACILITY_ID" NUMBER(38,0) NOT NULL ENABLE,
	"FACILITY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"OU_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"FACILITY_ABBREV" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("FACILITY_SK")
  );

CREATE TABLE "DIM_LOCATION" 
   ("LOCATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOCATION_ID" NUMBER(38,0) NOT NULL ENABLE,
	"LOCATION_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOCATION_ABBREV" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"FACILITY_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("LOCATION_SK")
  );

CREATE TABLE "DIM_MEASURE_AGE_GROUP" 
   ("AGE_GROUP_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"AGE_GROUP_ID" NUMBER(38,0) NOT NULL ENABLE,
	"QUALITY_MEASURE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"START_AGE" NUMBER(38,0) NOT NULL ENABLE,
	"END_AGE" NUMBER(38,0) NOT NULL ENABLE,
	"AGE_GROUP" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("AGE_GROUP_SK")
  );

CREATE TABLE "DIM_MEDICATION" 
   ("MEDICATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MEDICATION_ID" NUMBER(38,0) NOT NULL ENABLE,
	"MEDICATION_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"NDC_CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("MEDICATION_SK")
  );

CREATE TABLE "DIM_MEMBER" 
   ("MEMBER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MEMBER_ID" NUMBER(38,0) NOT NULL ENABLE,
	"GENDER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DATE_OF_BIRTH_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DATE_OF_DEATH_SK" VARCHAR2(100 BYTE),
	"FIRST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MIDDLE_NAME" VARCHAR2(100 BYTE),
	"LAST_NAME" VARCHAR2(100 BYTE),
	"ADDRESS1" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ADDRESS2" VARCHAR2(100 BYTE),
	"CITY" VARCHAR2(100 BYTE),
	"STATE" VARCHAR2(100 BYTE),
	"ZIP" VARCHAR2(100 BYTE),
	"COUNTY_NAME" VARCHAR2(100 BYTE),
	"COUNTRY_NAME" VARCHAR2(100 BYTE),
	"PHONE" VARCHAR2(100 BYTE),
	"EMAIL_ADDRESS" VARCHAR2(100 BYTE),
	"MARITAL_STATUS" VARCHAR2(100 BYTE),
	"LANGUAGE" VARCHAR2(100 BYTE),
	"LNGTD" VARCHAR2(100 BYTE),
	"LATTD" VARCHAR2(100 BYTE),
	"ETHNICITY" VARCHAR2(100 BYTE),
	"IMAGE_PATH" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("MEMBER_SK")
  );

CREATE TABLE "DIM_OU" 
   ("OU_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"OU_ID" NUMBER(38,0) NOT NULL ENABLE,
	"OU_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("OU_SK")
  );

CREATE TABLE "DIM_PATIENT" 
   ("PATIENT_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PAT_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PTY_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"EMR_PAT_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PAT_SSN" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PAT_MRN" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PAT_FIRST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PAT_MIDDLE_NAME" VARCHAR2(100 BYTE),
	"PAT_LAST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ADD_LINE_1" VARCHAR2(100 BYTE),
	"ADD_LINE_2" VARCHAR2(100 BYTE),
	"PAT_CITY" VARCHAR2(100 BYTE),
	"PAT_STATE" VARCHAR2(100 BYTE),
	"COUNTY" VARCHAR2(100 BYTE),
	"COUNTRY" VARCHAR2(100 BYTE),
	"ZIP" NUMBER(38,0),
	"RACE" VARCHAR2(100 BYTE),
	"ETHNICITY" VARCHAR2(100 BYTE),
	"GENDER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DATE_OF_BIRTH_SK" VARCHAR2(100 BYTE),
	"DATE_OF_DEATH_SK" VARCHAR2(100 BYTE),
	"EMAIL_ADDRESS" VARCHAR2(100 BYTE),
	"MARITAL_STATUS" VARCHAR2(100 BYTE),
	"LANGUAGE" VARCHAR2(100 BYTE),
	"LNGTD" VARCHAR2(100 BYTE),
	"LATTD" VARCHAR2(100 BYTE),
	"IMAGE_PATH" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("PATIENT_SK")
  );

CREATE TABLE "DIM_PAYER" 
   ("PAYER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PAYER_ID" NUMBER(38,0) NOT NULL ENABLE,
	"PAYER_NAME" VARCHAR2(100 BYTE),
	"PAYER_DESCRIPTION" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("PAYER_SK")
  );

CREATE TABLE "DIM_PHARMACY" 
   ("PHARMACY_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PHARMACY_ID" NUMBER(38,0) NOT NULL ENABLE,
	"PHARMACY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DISPLAY_NAME" VARCHAR2(100 BYTE),
	"NPI" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOCATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"TYPE_OF_NAME" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("PHARMACY_SK")
   );

CREATE TABLE "DIM_PRODUCT_PLAN" 
   ("PRODUCT_PLAN_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PRODUCT_PLAN_ID" NUMBER(38,0) NOT NULL ENABLE,
	"PAYER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOB_ID" NUMBER(38,0) NOT NULL ENABLE,
	"PRODUCT_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"NETWORK_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"PLAN_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PRODUCT_PLAN_START_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PRODUCT_PLAN_END_DATE_SK" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("PRODUCT_PLAN_SK")
  );

CREATE TABLE "DIM_PROVIDER" 
   ("PROVIDER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PROV_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PROV_TYPE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"EMR_USER_ID" VARCHAR2(100 BYTE),
	"EMR_ID" VARCHAR2(100 BYTE),
	"MDM_ID" VARCHAR2(100 BYTE),
	"UPIN" VARCHAR2(100 BYTE),
	"CLINICIAN_TITLE" VARCHAR2(100 BYTE),
	"EXTERNAL_NAME" VARCHAR2(100 BYTE),
	"DEA_NUMBER" VARCHAR2(100 BYTE),
	"EMAIL" VARCHAR2(100 BYTE),
	"GENDER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DATE_OF_BIRTH_SK" VARCHAR2(100 BYTE),
	"PTY_ID" VARCHAR2(100 BYTE),
	"FOUNDATION_NAME" VARCHAR2(100 BYTE),
	"MEDICARE_ID" VARCHAR2(100 BYTE),
	"BILLING_TAX_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LAST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ADDRESS1" VARCHAR2(100 BYTE),
	"ADDRESS2" VARCHAR2(100 BYTE),
	"CITY" VARCHAR2(100 BYTE),
	"STATE" VARCHAR2(100 BYTE),
	"ZIP" VARCHAR2(100 BYTE),
	"PHONE" VARCHAR2(100 BYTE),
	"SPECIALITY_1" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"SPECIALITY_2" VARCHAR2(100 BYTE),
	"SPECIALITY_3" VARCHAR2(100 BYTE),
	"PROVIDER_NPI" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"SPEC_ACTIVATION_ST_DATE_SK" VARCHAR2(100 BYTE),
	"SPEC_ACTIVATION_END_DATE_SK" VARCHAR2(100 BYTE),
	"TAXANOMY" VARCHAR2(100 BYTE),
	"RENDERING_PROVIDER_LICENSE" VARCHAR2(100 BYTE),
	"LICENSURE_CODE" VARCHAR2(100 BYTE),
	"CONTRACT_FLAG" VARCHAR2(100 BYTE),
	"PROVIDER_BUSINESS_NAME_OR_GRP" VARCHAR2(100 BYTE),
	"PG_ID" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("PROVIDER_SK")
  );

CREATE TABLE "DIM_QUALITY_MEASURE" 
   ("QUALITY_MEASURE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"QUALITY_MEASURE_ID" NUMBER(38,0),
	"QUALITY_PROGRAM_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MEASURE_TITLE" VARCHAR2(1000 BYTE),
	"DESCRIPTION" VARCHAR2(1000 BYTE),
	"TARGET_POPULATION_AGE" VARCHAR2(100 BYTE),
	"NUMERATOR" VARCHAR2(1000 BYTE),
	"DENOMINATOR" VARCHAR2(1000 BYTE),
	"DENO_EXCLUSIONS" VARCHAR2(1000 BYTE),
	"NUM_EXCLUSIONS" VARCHAR2(1000 BYTE),
	"DENO_EXCEPTIONS" VARCHAR2(1000 BYTE),
	"NUM_EXCEPTIONS" VARCHAR2(1000 BYTE),
	"NQS_DOMAIN" VARCHAR2(100 BYTE),
	"TYPE" VARCHAR2(100 BYTE),
	"CLINICAL_CONDITIONS" VARCHAR2(100 BYTE),
	"SUBCONDITIONS" VARCHAR2(100 BYTE),
	"STEWARD" VARCHAR2(1000 BYTE),
	"DATA_SOURCES" VARCHAR2(100 BYTE),
	"MEASURE_GROUPS" VARCHAR2(100 BYTE),
	"CARE_SETTINGS" VARCHAR2(100 BYTE),
	"REPORTING_LEVEL" VARCHAR2(100 BYTE),
	"IS_ACTIVE" VARCHAR2(1 BYTE),
	"PRIORITY" VARCHAR2(100 BYTE),
	"START_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"END_DATE_SK" VARCHAR2(100 BYTE),
	"DECILE1_START" FLOAT(126),
	"DECILE1_END" FLOAT(126),
	"DECILE2_START" FLOAT(126),
	"DECILE2_END" FLOAT(126),
	"DECILE3_START" FLOAT(126),
	"DECILE3_END" FLOAT(126),
	"DECILE4_START" FLOAT(126),
	"DECILE4_END" FLOAT(126),
	"DECILE5_START" FLOAT(126),
	"DECILE5_END" FLOAT(126),
	"DECILE6_START" FLOAT(126),
	"DECILE6_END" FLOAT(126),
	"DECILE7_START" FLOAT(126),
	"DECILE7_END" FLOAT(126),
	"DECILE8_START" FLOAT(126),
	"DECILE8_END" FLOAT(126),
	"DECILE9_START" FLOAT(126),
	"DECILE9_END" FLOAT(126),
	"DECILE10_START" FLOAT(126),
	"DECILE10_END" FLOAT(126),
	"MAX_SCORE" NUMBER(38,0),
	"TARGET_SCORE" FLOAT(126),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("QUALITY_MEASURE_SK")
  );

CREATE TABLE "DIM_QUALITY_PERCENTILE" 
   ("QUALITY_PERCENTILE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"QUALITY_PERCENTILE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"QUALITY_MEASURE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"P50" FLOAT(126) NOT NULL ENABLE,
	"P90" FLOAT(126) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("QUALITY_PERCENTILE_SK")
  );

CREATE TABLE "DIM_QUALITY_PROGRAM" 
   ("QUALITY_PROGRAM_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"QUALITY_PROGRAM_ID" NUMBER(38,0) NOT NULL ENABLE,
	"PROGRAM_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CATEGORY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MAX_POINTS" VARCHAR2(100 BYTE),
	"MAX_SCORE" VARCHAR2(100 BYTE),
	"START_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"END_DATE_SK" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("QUALITY_PROGRAM_SK")
  );

CREATE TABLE "DIM_RESOURCE" 
   ("RESOURCE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"RESOURCE_ID" NUMBER(38,0),
	"RESOURCE_NAME" VARCHAR2(100 BYTE),
	"RESOURCE_DESCRIPTION" VARCHAR2(100 BYTE),
	"COMMISSION_START_DATE_SK" VARCHAR2(100 BYTE),
	"COMMISSION_END_DATE_SK" VARCHAR2(100 BYTE),
	"MACHINE_UTIL_ID" NUMBER(38,0) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("RESOURCE_SK")
  );

CREATE TABLE "DIM_SPECIALITY_MEASURE" 
   ("SPECIALITY_MEASURE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"SPECIALITY_MEASURE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"MEASURE_NAME" VARCHAR2(100 BYTE),
	"PROGRAM" VARCHAR2(100 BYTE),
	"MEASURE_TYPE" VARCHAR2(100 BYTE),
	"MEASURE_DESCRIPTION" VARCHAR2(1000 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("SPECIALITY_MEASURE_SK")
  );

CREATE TABLE "DIM_TIME" 
   ("TIME_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"STANDARDTIME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"MIL_HH_MI_SS" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"HH_MI_SS" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"MIL_HH_MI" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"HH_MI" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"MIL_HH" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"HH" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"MI" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"SS" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"AMPM" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("TIME_SK")
  );
  
/*===============================================================================================================================================
 DDL for FACT_TABLES 
=================================================================================================================================================*/

CREATE TABLE "FACT_CLAIMS" 
   ("CLAIMS_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CLAIMS_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CLAIM_LINE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MEMBER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"START_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"END_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ADMIT_DATE_SK" VARCHAR2(100 BYTE),
	"PRIMARY_DIAGNOSIS" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DIAGNOSIS_CODE_2" VARCHAR2(100 BYTE),
	"DIAGNOSIS_CODE_3" VARCHAR2(100 BYTE),
	"DIAGNOSIS_CODE_4" VARCHAR2(100 BYTE),
	"DIAGNOSIS_CODE_5" VARCHAR2(100 BYTE),
	"DIAGNOSIS_CODE_6" VARCHAR2(100 BYTE),
	"DIAGNOSIS_CODE_7" VARCHAR2(100 BYTE),
	"DIAGNOSIS_CODE_8" VARCHAR2(100 BYTE),
	"DIAGNOSIS_CODE_9" VARCHAR2(100 BYTE),
	"PROCEDURE_CODE" VARCHAR2(100 BYTE),
	"PROCEDURE_CODE_MODIFIER" VARCHAR2(100 BYTE),
	"PROCEDURE_HCPCS_CODE" VARCHAR2(100 BYTE),
	"PROCEDURE_HCPCS_MDFR1_CD" VARCHAR2(10 BYTE),
	"PROCEDURE_HCPCS_MDFR2_CD" VARCHAR2(10 BYTE),
	"PROCEDURE_HCPCS_MDFR3_CD" VARCHAR2(10 BYTE),
	"PROCEDURE_HCPCS_MDFR4_CD" VARCHAR2(10 BYTE),
	"PROCEDURE_HCPCS_MDFR5_CD" VARCHAR2(10 BYTE),
	"LAB_CODE" VARCHAR2(100 BYTE),
	"BILL_TYPE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"POS_CODE_ID" VARCHAR2(100 BYTE),
	"DRG_CODE" VARCHAR2(100 BYTE),
	"CLAIM_TYPE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"REVENUE_CODE_ID" VARCHAR2(100 BYTE),
	"DISCHARGE_STATUS_CODE" VARCHAR2(100 BYTE),
	"PROVIDER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOCATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"AMOUNT_PAID" NUMBER(38,0),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("CLAIMS_SK")
  );

CREATE TABLE "FACT_EMR_CLAIM" 
   ("EMR_CLAIM_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"EHR_CLAIM_ID" NUMBER(38,0) NOT NULL ENABLE,
	"PATIENT_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ORIG_CLAIM_NUM" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DATE_RECEIVED_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ADMISSION_DATE_SK" VARCHAR2(100 BYTE),
	"OU_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"COVERAGE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"PAYER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PRODUCT_PLAN_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"SERVICE_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PROVIDER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"EXTERNAL_CLAIM_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"TOT_CHARGED_AMT" FLOAT(126),
	"ICD_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PCP_PROVIDER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOCATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ORIG_REV_CLM_ID" NUMBER(38,0),
	"ADJST_CLM_ID" NUMBER(38,0),
	"ORIG_ADJST_CLM_ID" NUMBER(38,0),
	"LOB_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"SERVICE_START_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"SERVICE_END_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"OTHER_PROV_SK" VARCHAR2(100 BYTE),
	"OPERATING_PROV_ID_SK" VARCHAR2(100 BYTE),
	"ATTEND_PROV_ID_SK" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("EMR_CLAIM_SK")
   );

CREATE TABLE "FACT_ENC" 
   ("ENC_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PATIENT_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ENC_CSN_ID" NUMBER(38,0) NOT NULL ENABLE,
	"AGE" FLOAT(126) NOT NULL ENABLE,
	"FIN_CLASS" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"BP_SYSTOLIC" NUMBER(38,0) NOT NULL ENABLE,
	"BP_DIALSTOLIC" NUMBER(38,0) NOT NULL ENABLE,
	"PULSE" NUMBER(38,0) NOT NULL ENABLE,
	"RESPIRATIONS" NUMBER(38,0) NOT NULL ENABLE,
	"ENC_CLOSED" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ENC_CLOSED_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOS_PRIM_PROC_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOS_MODIFIER1_ID" VARCHAR2(20 BYTE),
	"LOS_MODIFIER2_ID" VARCHAR2(20 BYTE),
	"LOS_MODIFIER3_ID" VARCHAR2(20 BYTE),
	"LOS_MODIFIER4_ID" VARCHAR2(20 BYTE),
	"APPT_STATUS_ID" NUMBER(38,0) NOT NULL ENABLE,
	"APPT_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"APPT_TIME_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"APPT_LENGTH" NUMBER(38,0),
	"HOSP_ADMSN_DATE_SK" VARCHAR2(100 BYTE),
	"HOSP_ADMSN_TIME_SK" VARCHAR2(100 BYTE),
	"HOSP_DISCHRG_DATE_SK" VARCHAR2(100 BYTE),
	"HOSP_DISCHRG_TIME_SK" VARCHAR2(100 BYTE),
	"CLAIM_ID" NUMBER(38,0) NOT NULL ENABLE,
	"LOS_PROC_CODE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ENCOUNTER_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PCP_PROV_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ATTEND_PROV_SK" VARCHAR2(100 BYTE),
	"ORDERING_PROV_SK" VARCHAR2(100 BYTE),
	"HEIGHT" VARCHAR2(100 BYTE),
	"WEIGHT" FLOAT(126),
	"BMI" FLOAT(126),
	"SMOKING_STATUS_ID" NUMBER(38,0),
	"TOBACCO_USE_VRFY_YN" VARCHAR2(1 BYTE),
	"DEPARTMENT_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOCATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"TEMPERATURE" FLOAT(126) NOT NULL ENABLE,
	"ACCOUNT_ID" NUMBER(38,0) NOT NULL ENABLE,
	"HSP_ACCOUNT_ID" NUMBER(38,0),
	"VISIT_REASON" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"COVERAGE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ENC_TYPE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ENCOUNTER_STATUS_ID" NUMBER(38,0) NOT NULL ENABLE,
	"DISCH_DATE_SK" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("ENC_SK")
  );

CREATE TABLE "FACT_ENC_DX" 
   ("ENC_DX_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ENC_CSN_ID" NUMBER(38,0) NOT NULL ENABLE,
	"ICD_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DX_LINE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CONTACT_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PRIMARY_DX_YN" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ENC_ICD_CODE" VARCHAR2(100 BYTE),
	"DX_CHRONIC_YN" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"DX_ED_YN" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"DX_UNIQUE" NUMBER(38,0) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("ENC_DX_SK")
   );

CREATE TABLE "FACT_HCC_RISK_SCORE" 
   ("HCC_RISK_SCORE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MEMBER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"HCC_FINAL_LIST" VARCHAR2(100 BYTE),
	"HCC_SCORE" FLOAT(126),
	"HCC_GAPS" NUMBER(38,0),
	"DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("HCC_RISK_SCORE_SK")
  );

CREATE TABLE "FACT_HEDIS_GAPS_IN_CARE" 
   ("HEDIS_GAPS_IN_CARE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MEMBER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PRODUCT_PLAN_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"QUALITY_MEASURE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"IN_DENOMINATOR" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"IN_DENOMINATOR_EXCLUSION" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"IN_DENOMINATOR_EXCEPTION" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"IN_NUMERATOR" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"IN_NUMERATOR_EXCLUSION" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"IN_NUMERATOR_EXCEPTION" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REASON" VARCHAR2(1000 BYTE),
	"FACILITY_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("HEDIS_GAPS_IN_CARE_SK")
  );

CREATE TABLE "FACT_HEDIS_QMS" 
   ("HEDIS_QMS_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"QUALITY_MEASURE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"FACILITY_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOB_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PRODUCT_PLAN_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"NUMERATOR" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DENOMINATOR" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"RATIO" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"NUM_EXCLUSION" VARCHAR2(100 BYTE),
	"DENO_EXCLUSION" VARCHAR2(100 BYTE),
	"NUM_EXCEPTION" VARCHAR2(100 BYTE),
	"DENO_EXCEPTION" VARCHAR2(100 BYTE),
	"PERFORMANCE" VARCHAR2(100 BYTE),
	"BONUS" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("HEDIS_QMS_SK")
  );

CREATE TABLE "FACT_MAMMO_REPORTING" 
   ("MAMMO_REPORTING_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MAMMO_REPORTING_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"SPECIALITY_MEASURE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"START_OF_PERIOD_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOCATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"FINALIZING_PROVIDER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"AGE_GROUP_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"BI_RAD_CODE" NUMBER(38,0),
	"NUMERATOR" NUMBER(38,0),
	"DENOMINATOR" NUMBER(38,0),
	"RATIO" FLOAT(126),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("MAMMO_REPORTING_SK")
  );

CREATE TABLE "FACT_MEM_COMORBIDITY" 
   ("MEM_COMORBIDITY_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MEMBER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ALZHEIMER_AND_RELATED_DEMENTIA" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ARTHRITIS" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ASTHMA" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ATRIAL_FIBRILLATION" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"AUTISM_SPECTRUM_DISORDERS" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"BREAST_CANCER" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"CHRONIC_KIDNEY_DISEASE" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"COPD" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"DEPRESSION" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"DIABETES" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"HEART_FAILURE" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"HEPATITIS" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"HIV/AIDS" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"HYPERLIPIDEMIA" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"HYPERTENSION" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ISCHEMIC_HEART_DISEASE" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"OSTEOPOROSIS" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"SCHIZOPHRENIA_AND_PSYCHOTIC" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"STROKE" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"COLORECTAL_CANCER" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"LUNG_CANCER" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"PROSTATE_CANCER" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"CHRONIC_DISEASE_1" VARCHAR2(1 BYTE),
	"CHRONIC_DISEASE_2" VARCHAR2(1 BYTE),
	"CHRONIC_DISEASE_3" VARCHAR2(1 BYTE),
	"COMORBIDITY_COUNT" NUMBER(38,0) NOT NULL ENABLE,
	"DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("MEM_COMORBIDITY_SK")
   );

CREATE TABLE "FACT_MEMBERSHIP" 
   ("MEMBERSHIP_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MEMBER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MEMBER_PLAN_START_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MEMBER_PLAN_END_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PRODUCT_PLAN_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PRIMARY_HOLDER" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"LOB_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PRIMARY_PAYER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"SECONDARY_PAYER_SK" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("MEMBERSHIP_SK")
  );

CREATE TABLE "FACT_MIPS_GAPS_IN_CARE" 
   ("MIPS_GAPS_IN_CARE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PATIENT_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"QUALITY_MEASURE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"IN_DENOMINATOR" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"IN_DENOMINATOR_EXCLUSION" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"IN_DENOMINATOR_EXCEPTION" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"IN_NUMERATOR" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"IN_NUMERATOR_EXCLUSION" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"IN_NUMERATOR_EXCEPTION" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"LOCATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("MIPS_GAPS_IN_CARE_SK")
  );

CREATE TABLE "FACT_MIPS_QMS" 
   ("MIPS_QMS_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"QUALITY_MEASURE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOCATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"NUMERATOR" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DENOMINATOR" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"RATIO" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"IA_RESULT" VARCHAR2(100 BYTE),
	"NUM_EXCLUSION" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DENO_EXCLUSION" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"NUM_EXCEPTION" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DENO_EXCEPTION" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PERFORMANCE" VARCHAR2(100 BYTE),
	"BONUS" VARCHAR2(100 BYTE),
	"SCORE" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("MIPS_QMS_SK")
  );

CREATE TABLE "FACT_MIPS_SCORE" 
   ("MIPS_SCORE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOCATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"QUALITY_PROGRAM_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PERFORMANCE_POINTS" NUMBER(38,0) NOT NULL ENABLE,
	"BONUS_POINTS" NUMBER(38,0) NOT NULL ENABLE,
	"SCORE" NUMBER(38,0) NOT NULL ENABLE,
	"TOTAL_PAYMENT" NUMBER(38,0) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("MIPS_SCORE_SK")
  );

CREATE TABLE "FACT_OBS" 
   ("OBS_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ENC_CSN_ID" NUMBER(38,0) NOT NULL ENABLE,
	"ENC_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"START_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"END_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"READMIT_START_DATE_SK" VARCHAR2(100 BYTE),
	"READMIT_END_DATE_SK" VARCHAR2(100 BYTE),
	"LOCATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DELIVERY_TYPE" VARCHAR2(100 BYTE),
	"DELIVERY_HTN" VARCHAR2(1 BYTE),
	"DELIVERY_PAT_CLASS" VARCHAR2(100 BYTE),
	"READMISSION" VARCHAR2(1 BYTE),
	"READMIT_HTN" VARCHAR2(1 BYTE),
	"READMIT_PAT_CLASS" VARCHAR2(100 BYTE),
	"READMIT_DAYS" NUMBER(38,0),
	"BP_CRITERIA_MET" VARCHAR2(1 BYTE),
	"HTN_TYPE" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("OBS_SK")
  );

CREATE TABLE "FACT_ORDER_MED" 
   ("ORDER_MED_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ENC_CSN_ID" NUMBER(38,0) NOT NULL ENABLE,
	"ORDER_ID" NUMBER(38,0) NOT NULL ENABLE,
	"MEDICATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ORDERING_PROV_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"AUTHORIZING_PROV_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ADMINISTERED_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ORDER_MODE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ORDER_STATUS_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ICD_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DOSE" FLOAT(126),
	"DOSE_UNIT" VARCHAR2(100 BYTE),
	"FREQUENCY" VARCHAR2(100 BYTE),
	"NDC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"INSTRUCTIONS" VARCHAR2(100 BYTE),
	"ORDER_CLASS" NUMBER(38,0),
	"ORDER_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ORDER_REASON" VARCHAR2(100 BYTE),
	"PHARMACY_SK" VARCHAR2(100 BYTE),
	"ROUTE_C" NUMBER(38,0),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("ORDER_MED_SK")
  );

CREATE TABLE "FACT_ORDER_PROC" 
   ("ORDER_PROC_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ENC_CSN_ID" NUMBER(38,0) NOT NULL ENABLE,
	"ORDER_ID" NUMBER(38,0) NOT NULL ENABLE,
	"PROCEDURE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PROCEDURE_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ORDERING_PROV_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"AUTHORIZING_PROV_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ORDER_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"RESULT_DATE_SK" VARCHAR2(100 BYTE),
	"ORDER_STATUS_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ORDER_MODE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"RESULT_STATUS_ID" VARCHAR2(100 BYTE),
	"ICD_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ORDER_TYPE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ACCESSION_NO" VARCHAR2(100 BYTE),
	"ORDER_REASON" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("ORDER_PROC_SK")
  );

CREATE TABLE "FACT_ORDER_RESULTS" 
   ("ORDER_RESULT_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ORDER_PROC_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PATIENT_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ENC_CSN_ID" NUMBER(38,0) NOT NULL ENABLE,
	"LINE" NUMBER(38,0) NOT NULL ENABLE,
	"RESULT_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"RESULT_VALUE" VARCHAR2(100 BYTE),
	"UNIT" VARCHAR2(100 BYTE),
	"LAB_NAME" VARCHAR2(100 BYTE),
	"RESULT_STATUS_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"RESULT_ID" NUMBER(38,0),
	"LOINC_CODE" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("ORDER_RESULT_SK")
   );

CREATE TABLE "FACT_RAD" 
   ("RAD_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ENC_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ENC_CSN_ID" NUMBER(38,0) NOT NULL ENABLE,
	"RESOURCE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"IMAGE_PERF_LOC_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"AGE_GROUP_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOCATION_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"REV_LOC_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PROVIDER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PATIENT_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DEPARTMENT_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ICD_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PROCEDURE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"EXAM_START_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"EXAM_END_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"BI_RAD_CODE" NUMBER(38,0),
	"TUMOR_SIZE" NUMBER(38,0),
	"MALIGNANCY_TYPE" VARCHAR2(100 BYTE),
	"SPECIMEN_ID" VARCHAR2(100 BYTE),
	"TISSUE_TYPE" VARCHAR2(100 BYTE),
	"CLASSIFICATION_OF_LESION" VARCHAR2(100 BYTE),
	"INDICATION_FOR_EXAM" VARCHAR2(100 BYTE),
	"ED_ARRIVAL_DATE_SK" VARCHAR2(100 BYTE),
	"ED_ARRIVAL_TIME_SK" VARCHAR2(100 BYTE),
	"CT_ORDER_DATE_SK" VARCHAR2(100 BYTE),
	"CT_ORDER_TIME_SK" VARCHAR2(100 BYTE),
	"PAT_ARRIVAL_DATE_SK" VARCHAR2(100 BYTE),
	"PAT_ARRIVAL_TIME_SK" VARCHAR2(100 BYTE),
	"CT_START_DATE_SK" VARCHAR2(100 BYTE),
	"CT_START_TIME_SK" VARCHAR2(100 BYTE),
	"CT_END_DATE_SK" VARCHAR2(100 BYTE),
	"CT_END_TIME_SK" VARCHAR2(100 BYTE),
	"RAD_READ_START_DATE_SK" VARCHAR2(100 BYTE),
	"RAD_READ_START_TIME_SK" VARCHAR2(100 BYTE),
	"RAD_READ_END_DATE_SK" VARCHAR2(100 BYTE),
	"RAD_READ_END_TIME_SK" VARCHAR2(100 BYTE),
	"TPA_ADMINISTERED_DATE_SK" VARCHAR2(100 BYTE),
	"TPA_ADMINISTERED_TIME_SK" VARCHAR2(100 BYTE),
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("RAD_SK")
  );

CREATE TABLE "FACT_RX_CLAIM" 
   ("RX_CLAIM_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"RX_CLAIM_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"RX_CLAIM_LINE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MEMBER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"NDC_NUMBER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"GENERIC_INDICATOR" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DAYS_SUPPLIED" NUMBER(38,0) NOT NULL ENABLE,
	"FORMULARY_INDICATOR" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"QUANTITY" NUMBER(38,0) NOT NULL ENABLE,
	"UNIT" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PROVIDER_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"AMOUNT_PAID" FLOAT(126),
	"START_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"END_DATE_SK" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CURR_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 PRIMARY KEY ("RX_CLAIM_SK")
   );

/*===============================================================================================================================================
 DDL for REF_TABLES 
=================================================================================================================================================*/

CREATE TABLE "REF_APPT_STATUS" 
   ("APPT_STATUS_ID" NUMBER(38,0) NOT NULL ENABLE,
	"APPT_STATUS_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_BILL_TYPE" 
   ("BILL_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"BILL_TYPE_CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"BILL_TYPE_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_CLAIM_TYPE" 
   ("CLAIM_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"CLAIM_TYPE_CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CLAIM_TYPE_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_ENC_STATUS" 
   ("ENC_STATUS_ID" NUMBER(38,0) NOT NULL ENABLE,
	"ENC_STATUS_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_ENC_TYPE" 
   ("ENC_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"ENC_TYPE_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_HEDIS2016" 
   ("MEASUREID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MEASURENAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"VALUESET" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DEFINITION" VARCHAR2(500 BYTE),
	"CODESYSTEM" VARCHAR2(100 BYTE),
	"CODESYSTEMVERSION" VARCHAR2(100 BYTE),
	"VALUESETOID" VARCHAR2(100 BYTE),
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_ICD" 
   ("ICD_ID" NUMBER(38,0) NOT NULL ENABLE,
	"ICD_NAME" VARCHAR2(500 BYTE) NOT NULL ENABLE,
	"CCS_CATEGORY_DESC" VARCHAR2(500 BYTE),
	"CODE_TYPE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_LOB" 
   ("LOB_ID" NUMBER(38,0) NOT NULL ENABLE,
	"LOB_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LOB_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_MACHINE_UTIL" 
   ("MACHINE_UTIL_ID" NUMBER(38,0) NOT NULL ENABLE,
	"RESOURCE_NAME" VARCHAR2(100 BYTE),
	"HOURS_AVAILABLE" FLOAT(126),
	"MACHINE_TIME" FLOAT(126),
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_MED_VALUE_SET" 
   ("MEASURE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MEASURE_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"MEDICATION_LIST" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"NDC_CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"BRAND_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"GENERIC_PRODUCT_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ROUTE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DRUG_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DRUG_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PACKAGE_SIZE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"UNIT" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"DOSE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"FORM" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MED_CONVERSION_FACTOR" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_NETWORK_TYPE" 
   ("NETWORK_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"NETWORK_TYPE_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_ORDER_MODE" 
   ("ORDER_MODE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"ORDER_MODE_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_ORDER_RESULT_STATUS" 
   ("RESULT_STATUS_ID" NUMBER(38,0) NOT NULL ENABLE,
	"RESULT_STATUS_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_ORDER_STATUS" 
   ("ORDER_STATUS_ID" NUMBER(38,0) NOT NULL ENABLE,
	"ORDER_STATUS_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_ORDER_TYPE" 
   ("ORDER_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"ORDER_TYPE_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_PLAN_COVERAGE" 
   ("COVERAGE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"COVERAGE_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_POS" 
   ("POS_CODE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"POS_CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"POS_CODE_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_PROCEDURES" 
   ("PROCEDURE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"PROCEDURE_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PROCEDURE_CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"PROCEDURE_TYPE" VARCHAR2(100 BYTE),
	"PROCEDURE_GROUP" VARCHAR2(100 BYTE),
	"PROCEDURE_GROUP_NAME" VARCHAR2(100 BYTE),
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_REVENUE" 
   ("REVENUE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"REVENUE_CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"REVENUE_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "REF_SPECIALITY_CODES" 
   ("SPECIALITY_ID" NUMBER(38,0) NOT NULL ENABLE,
	"SPECIALITY_CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"SPECIALITY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"TAXONOMY_CODE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ACTIVE_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"LATEST_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"INGESTION_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"USER" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );

/*===============================================================================================================================================
 DDL for QMS_TABLES 
=================================================================================================================================================*/
   
CREATE TABLE "QMS_DATA_SOURCES" 
   ("DATA_SOURCE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"DATA_SOURCE_NAME" VARCHAR2(1500 BYTE) NOT NULL ENABLE, 
	"DATA_SOURCE_DESCRIPTION" VARCHAR2(1500 BYTE), 
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"CURRENT_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("DATA_SOURCE_ID")
   );

CREATE TABLE "QMS_MEASURE" 
   ("MEASURE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"MEASURE_EDIT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"QUALITY_PROGRAM_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"MEASURE_NAME" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"TARGET_POPULATION_AGE" VARCHAR2(2500 BYTE), 
	"NUMERATOR" VARCHAR2(4000 BYTE), 
	"DENOMINATOR" VARCHAR2(4000 BYTE), 
	"NUM_EXCLUSION" VARCHAR2(4000 BYTE), 
	"DENO_EXCLUSIONS" VARCHAR2(4000 BYTE), 
	"DOMAIN_ID" NUMBER(38,0), 
	"TYPE_ID" NUMBER(38,0), 
	"CLINICAL_CONDITIONS" VARCHAR2(2500 BYTE), 
	"STEWARD_ID" NUMBER(38,0), 
	"DATA_SOURCES_ID" VARCHAR2(2500 BYTE), 
	"IS_ACTIVE" VARCHAR2(1 BYTE), 
	"STATUS_ID" NUMBER(38,0), 
	"REVIEW_COMMENTS" VARCHAR2(4000 BYTE), 
	"AUTHOR_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"REVIEWER_ID" NUMBER(38,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"PRIORITY_FLAG" VARCHAR2(10 BYTE), 
	"DECILE1_START" NUMBER(7,2), 
	"DECILE1_END" NUMBER(7,2), 
	"DECILE2_START" NUMBER(7,2), 
	"DECILE2_END" NUMBER(7,2), 
	"DECILE3_START" NUMBER(7,2), 
	"DECILE3_END" NUMBER(7,2), 
	"DECILE4_START" NUMBER(7,2), 
	"DECILE4_END" NUMBER(7,2), 
	"DECILE5_START" NUMBER(7,2), 
	"DECILE5_END" NUMBER(7,2), 
	"DECILE6_START" NUMBER(7,2), 
	"DECILE6_END" NUMBER(7,2), 
	"DECILE7_START" NUMBER(7,2), 
	"DECILE7_END" NUMBER(7,2), 
	"DECILE8_START" NUMBER(7,2), 
	"DECILE8_END" NUMBER(7,2), 
	"DECILE9_START" NUMBER(7,2), 
	"DECILE9_END" NUMBER(7,2), 
	"DECILE10_START" NUMBER(7,2), 
	"DECILE10_END" NUMBER(7,2), 
	"MAX_SCORE" NUMBER(38,0), 
	"TARGET" NUMBER(7,2), 
	"CURRENT_FLAG" VARCHAR2(1 BYTE), 
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"MODIFIED_BY" NUMBER(38,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_QMS_MEASURE" PRIMARY KEY ("MEASURE_ID", "MEASURE_EDIT_ID")
   );

CREATE TABLE "QMS_MEASURE_CONFIGURATOR" 
   ("MEASURE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"CATEGORY_LINE_ID" NUMBER(38,0), 
	"OPERATOR" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"BUSINESS_EXPRESSION" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"TECHNICAL_EXPRESSION" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"VERSION" NUMBER(38,0), 
	"STATUS" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"CURRENT_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(4000 BYTE) NOT NULL ENABLE
   );

CREATE TABLE "QMS_MEASURE_DOMAIN" 
   ("MEASURE_DOMAIN_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"MEASURE_DOMAIN_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MEASURE_DOMAIN_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"CURRENT_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("MEASURE_DOMAIN_ID")
   );

CREATE TABLE "QMS_MEASURE_STATUS" 
   ("MEASURE_STATUS_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"MEASURE_STATUS_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MEASURE_STATUS_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"CURRENT_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("MEASURE_STATUS_ID")
   );

CREATE TABLE "QMS_MEASURE_STEWARD" 
   ("STEWARD_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"STEWARD_NAME" VARCHAR2(1500 BYTE) NOT NULL ENABLE, 
	"STEWARD_DESCRIPTION" VARCHAR2(1500 BYTE), 
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"CURRENT_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("STEWARD_TYPE_ID")
   );

CREATE TABLE "QMS_MEASURE_TYPE" 
   ("MEASURE_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"MEASURE_TYPE_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MEASURE_TYPE_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"CURRENT_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("MEASURE_TYPE_ID")
   );

CREATE TABLE "QMS_PROGRAM_LIST" 
   ("PROGRAM_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PROGRAM_NAME" VARCHAR2(1000 BYTE), 
	"REC_CREATE_DATE" TIMESTAMP (6), 
	"REC_UPDATE_DATE" TIMESTAMP (6), 
	"ACTIVE_FLAG" VARCHAR2(1 BYTE), 
	 PRIMARY KEY ("PROGRAM_ID")
   );

CREATE TABLE "QMS_QUALITY_PROGRAM" 
   ("QUALITY_PROGRAM_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PROGRAM_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PROGRAM_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CATEGORY_NAME" VARCHAR2(100 BYTE), 
	"MAX_POINTS" NUMBER(38,0), 
	"MAX_SCORE" NUMBER(38,0), 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE, 
	"REC_CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"CURRENT_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("QUALITY_PROGRAM_ID")
   );

CREATE TABLE "QMS_STATUS" 
   ("STATUS_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"STATUS_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"REC_CREATE_DATE" TIMESTAMP (6), 
	"REC_UPDATE_DATE" TIMESTAMP (6), 
	"ACTIVE_FLAG" VARCHAR2(1 BYTE), 
	 PRIMARY KEY ("STATUS_ID")
   );

CREATE TABLE "QMS_USER_MASTER" 
   ("USER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"USER_LOGINID" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"USER_EMAIL" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"LAST_LOGIN" TIMESTAMP (6), 
	"USER_ROLE_ID" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"CURRENT_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("USER_ID")
   );

CREATE TABLE "QMS_USER_ROLE" 
   ("QMS_USER_ROLE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"QMS_USER_ROLE_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"QMS_USER_ROLE_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"REC_UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"CURRENT_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("QMS_USER_ROLE_ID")
   );